### ISSUE TITLE
This library does not work when minifyEnable=true. 

### ISSUE THREAD

**Issue by sushantp777** [akexorcist/Localization#85] opened 2021-01-13 07:31 UTC
This library fails when for the following parameters are set in any of the build types:
```
minifyEnabled true
shrinkResources true
```

**Comment by akexorcist** [comment] 2021-01-13 16:14
Can you tell me more about fails? Build failed? Runtime Exception? 

And does your app build as AAB with language splitting? If true, please disable the language splitting.

**Comment by akexorcist** [comment] 2021-01-13 16:37
Duplicate of #84

**Comment by bannarisoftwares** [comment] 2021-02-20 01:25
is this issue resolved?

**Comment by akexorcist** [comment] 2021-02-24 21:56
@bannarisoftwares 
Please give me some more information
* Do you enable the MultiDex in your app?
* Do you publish app as app bundle with language splitting?

**Comment by bannarisoftwares** [comment] 2021-03-05 09:40
> @bannarisoftwares
> Please give me some more information
> 
> * Do you enable the MultiDex in your app?
> * Do you publish app as app bundle with language splitting?

Yes... @akexorcist , I am able to enable the MultiDex in my app. Yes, I publish the app as an app bundle with language splitting. Link to my app [https://play.google.com/store/apps/details?id=com.softwares.bannari.whatstouch](url)

**Comment by akexorcist** [comment] 2021-03-06 18:30
@bannarisoftwares As I tried your app, language changing work fine. I also tested about MultiDex and minify in my tested project (see my comment in https://github.com/akexorcist/Localization/issues/84#issuecomment-788591478) but no problem found.

So I will close this issue soon.

**Closed as completed** 2021-03-08 13:16 UTC
