### ISSUE TITLE
Not work when switching system dark theme using compose isSystemInDarkTheme().

### ISSUE THREAD

**Issue by ccmtmp** [akexorcist/Localization#75] opened 2020-10-14 10:03 UTC
As title and I use below : 
- LocalizationActivity
- LocalizationApplication

Can change language, but cannot switch dark theme (compose's isSystemInDarkTheme()).

**Comment by akexorcist** [comment] 2021-02-24 22:02
Fix in https://github.com/akexorcist/Localization/commit/32095d834bb99f793902118ad88230ad870663ce and https://github.com/akexorcist/Localization/commit/3a35ade5ade2238fc0074b6ca0f43ec7c474b175 

But I have to do the full testing before release this because there're a lot of changes from these code.

**Comment by cmcheungapp** [comment] 2021-02-25 01:55
Great, thanks!

**Comment by akexorcist** [comment] 2021-03-01 19:32
Duplicate of #72

**Comment by akexorcist** [comment] 2021-03-06 18:59
@ccmtmp @cmcheungapp 1.2.7 is rolling out!

**Closed as completed** 2021-03-06 18:59 UTC
Labels: enhancement
